# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "9de6d3e438fa16fa19eb7a8f8eb5fda8105675f9ce8591a9eb725742f81c54f4"  # change this!
  public_instance: true
  allow_cors: true
  image_proxy: true
  base_url: http://127.0.0.1:8089/
# server:
#   # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
#   secret_key: "9de6d3e438fa16fa19eb7a8f8eb5fda8105675f9ce8591a9eb725742f81c54f4"  # change this!
#   # limiter: false  # enable this when running the instance for a public usage on the internet
#   # image_proxy: true
#   # server:
#   port: 8080
#   bind_address: "0.0.0.0"
#   secret_key: "CHANGE_ME"
#   public_instance: true
#   allow_cors: true
#   image_proxy: true
#   base_url: http://127.0.0.1:8089/
redis:
  url: redis://redis:6379/0
